full tasks
ikozitskiy/task pull request #1
Opened 2024-08-24 08:39 UTC by ikozitskiy

2024-08-24 11:13 UTC, olia-trofymchuk requested changes

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/__pycache__/buffer_page.cpython-38.pyc
краще не комітити файли __pycache__, оскільки вони є тимчасовими, специфічними для конкретного середовища та версії пайтона. 

якщо створюєш репозиторій, краще створити файл .gitignore, який не дасть тобі закомітити все непотрібне

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/__pycache__/db.cpython-38.pyc
аналогічно.
пропоную видалити і додати .gitignore,

2024-08-24 11:13 UTC, olia-trofymchuk commented on test_task1.py
> +db = Database()
перероби це під фікстуру (ти на співбесіді сам казав, чому так краще🙂)

бо в двох .py файлах ти ініціалізуєш екземпляр класу `Database` і використовуєш його у глобальному просторі (як доступним у всій області видимості файлу), що є не good practice.

2024-08-24 11:13 UTC, olia-trofymchuk commented on test_task2.py
зроби один файл із тестами в одному класі

2024-08-24 11:13 UTC, olia-trofymchuk commented on test_task2.py
> +    assert db.test_connection()
таку перевірку ти можеш додати відразу після того, як буде ініціалізована база 
так ти відразу дізнаєшся, чи все окей з конектом
для цього окремий тест не потрібен

2024-08-24 11:13 UTC, olia-trofymchuk commented on test_task2.py
> +
в кінці кожного файлу має бути один порожній рядок, щоб відповідати стандартам PEP8, і не більше одного. (дотримання лише одного порожнього рядка є звичною практикою серед Python-розробників для відповідності загальноприйнятим стилістичним рекомендаціям)

[PEP8: W292 No newline at end of file](https://peps.python.org/pep-0008/#blank-lines).

2024-08-24 11:13 UTC, olia-trofymchuk commented on test_task1.py
> +    assert len(product_name_elements)==len(data_from_db)
відповідно до PEP8, слід використовувати пробіли навколо операторів для покращення читабельності коду.
(це робить код більш зрозумілим і відповідає загальноприйнятим стандартам).

[PEP8: E225 missing whitespace around operator](https://peps.python.org/pep-0008/#pet-peeves)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/db.py
> +    def search_for_product(self,parameter):
відповідно до PEP8, після коми повинен бути пробіл для кращої читабельності коду.

[PEP8: E231 missing whitespace after ','](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/db.py
> +    def search_with_random_parameter(self,parameter):
відповідно до PEP8, після коми повинен бути пробіл для кращої читабельності коду.

[PEP8: E231 missing whitespace after ','](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +    def close(self):
ти написав метод по закриттю драйвера в класі `DriverSet` і такий самий метод в класі BufferPage (але з іншою назвою). 

`close` та `close_drv` - і не викликав хоча б один із методів ніде, тобто драйвер не закрив свій конект, що не є ок флоу.

згадай про наслідування і як цей метод можна використати в дочірніх класах.

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +    def __init__(self) -> None:
ти тут додав анотацію на повернення результату функції.
а зроби так всюди) 

це coding best practices

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +    def close(self):
відповідно до PEP8, між визначеннями методів у класі має бути один порожній рядок для покращення читабельності коду.

[PEP8: E301 expected 1 blank line, found 0](https://peps.python.org/pep-0008/#blank-lines)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +    def login(self):
відповідно до PEP8, між визначеннями методів у класі має бути один порожній рядок для покращення читабельності коду.

[PEP8: E301 expected 1 blank line, found 0](https://peps.python.org/pep-0008/#blank-lines)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +    def search_filtered_records(self,search_param):
відповідно до PEP8, між визначеннями методів у класі має бути один порожній рядок для покращення читабельності коду.

[PEP8: E301 expected 1 blank line, found 0](https://peps.python.org/pep-0008/#blank-lines)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +
відповідно до PEP8, між методами класу повинно бути не більше одного порожнього рядка. якщо порожніх рядків більше — це порушення стандарту.

[PEP8: E303 too many blank lines (2)](https://peps.python.org/pep-0008/#blank-lines)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +    def __init__(self):
відповідно до PEP8, між атрибутами класу та першим методом повинен бути один порожній рядок.

[PEP8: E302 expected 2 blank lines before class or function definition](https://peps.python.org/pep-0008/#blank-lines)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +    def get_quantity_for_product(self,parameter):
відповідно до PEP8, після коми повинен бути пробіл для кращої читабельності коду.

[PEP8: E231 missing whitespace after ','](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +    def search_filtered_records(self,search_param):
відповідно до PEP8, після коми повинен бути пробіл для кращої читабельності коду.

[PEP8: E231 missing whitespace after ','](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +        search_field = self.driver.find_element(By.ID, 'searchbar')
що я пропоную поліпшити в цьому методі: 

локатори, що використовуються в методі, можуть відволікати від основної логіки через їхню кількість та складність. 
рекомендую винести всі локатори в окремий файл або клас (наприклад, `locators.py`), де їх можна зберігати як константи. це поліпшить структуру коду та зробить його більш підтримуваним і читабельним.

потім можна просто імпортувати потрібні локатори та передавати їх у відповідні методи.
такий підхід дозволить зосередитись на логіці тесту, а не на пошуку елементів, і полегшить рефакторинг або оновлення локаторів у майбутньому.

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +        btn_login_elem = self.driver.find_element(By.CLASS_NAME, 'submit-row').click()
зроби так само, як я вказала в коментарі на 48 рядку


це про:

> рекомендую винести всі локатори в окремий файл або клас (наприклад, locators.py), де їх можна зберігати як константи. це поліпшить структуру коду та зробить його більш підтримуваним і читабельним.

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/db.py
> +        record = self.cursor.fetchall()
в назві методу вказано, що ти витягуєш рандомний запис, тобто він один. 

`fetchall` витягує всі записи. зроби виклик іншої функції, яка поверне тобі один рядок.

2024-08-24 11:13 UTC, olia-trofymchuk commented on test_task1.py
> +    status_elements = results[14]
ой, це дуже схоже на `boilerplate code` (щось на кшталт того, що код дуже примітивний і повторюваний)

зараз твій код містить багато елементів, що повторюються, а також посилання на дані за індексами, що може ускладнити підтримку та розуміння коду. 

давай спробуємо покращити код за допомогою словника, який дозволить зберігати відповідні елементи сторінки та бд у парі під зрозумілими ключами (це має зменшити кількість дублікацій)

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +        total_results = self.driver.find_element(By.CLASS_NAME, 'small.quiet').text
зроби так само, як я вказала в коментарі на 48 рядку

> це про:
рекомендую винести всі локатори в окремий файл або клас (наприклад, locators.py), де їх можна зберігати як константи. це поліпшить структуру коду та зробить його більш підтримуваним і читабельним.

2024-08-24 11:13 UTC, olia-trofymchuk commented on modules/buffer_page.py
> +class BufferPage(DriverSet):
**!!!в будь-якому випадку наслідування прибирай**

дивись, у цьому випадку є 2 підходи:
використати просту фікстурку для ініціалізації драйвера, яка автоматично завершить роботу драйвера після тесту або ж залишити клас, який може вміщувати в себе методи для взаємодії зі сторінками, але використовувати його не через наслідування. 

перший варіант зараз тобі ідеально підійде, бо
1. фікстура автоматично керує життєвим циклом драйвера (створення та закриття).
2. зменшується дублікація коду завдяки повторному використанню фікстури.

але якщо розглядати код на подальше розширення, то краще залишити клас. 
1. це дозволить організувати логіку взаємодії з елементами сторінок у вигляді методів (наприклад, методи для кліків, введення тексту).
2.  цей підхід дозволить розширювати функціонал без порушення принципів ООП, і в той же час використовувати фікстуру для автоматичного завершення роботи драйвера.

при цьому замість наслідування від класу, драйвер можна передавати як параметр у конструктор класу, що дозволить уникнути надлишкового наслідування.

2024-08-25 21:07 UTC, ikozitskiy commented on test_task1.py
> +db = Database()
Отут поки не прибираю виклик db для 1 функції бо не можу підібрати фікстуру для того щоб передати об'єкт в parametrize. Ще подумаю над цим

2024-08-26 07:02 UTC, merged